### ISSUE TITLE
Fixes on Jobs form

### ISSUE THREAD

**Issue by mergulhao** [Helabs/helabs.github.com#538]
We have a Jobs form: 
http://helabs.com.br/jobs-developer/
http://helabs.com.br/jobs-designer/ (it's hidden/commented) here.

What we should fix:
- [x] Make it look equal "Contact" form (http://helabs.com.br/fale-conosco/)
- [x] Move to use the same wufoo backend as "Contact" form
- [x] Fill "Interesse" hidden field with the word "Team" (see Startupdev form if in doubt: http://helabs.com.br/servicos/startupdev/)
- [x] Update Zapier to not update Pipedrive if "Interesse" hidden field equal a "Team"
- [x] Update Zapier to post on candidates Basecamp' project as it's done today with the current jobs form

@obetomuniz If you have any doubt, ask me, pls. :guitar:

**Comment by obetomuniz** [comment]
@mergulhao Okay, I'll work on it today.  :smile:

**Comment by obetomuniz** [comment]
@mergulhao Can you talk more about this item:

- [ ] Move to use the same wufoo backend as "Contact" form

It is to use the same URL of the form "Fale Conosco"?

#thx

**Comment by mergulhao** [comment]
@obetomuniz yes... look that the list is sorted. the third item only makes sense if the second is already done. I don't know how was possible to check the third before check the second...

**Comment by obetomuniz** [comment]
Yes, its possible :smile: 

I have created the filter in Zapier.

**Comment by obetomuniz** [comment]
Done.

@mergulhao Yourself is who will test the integration?

**Comment by mergulhao** [comment]
@obetomuniz It did not worked for me. When I submited I got this message from Wufoo: http://cl.ly/image/2n2d0S2w1d32

**Comment by mergulhao** [comment]
@obetomuniz I did some fixes there, take a look later. Take care with this things... If I did not tested it, It would go live broken...

**Comment by mergulhao** [comment]
Zapier is not working as expected... Look: http://cl.ly/image/1Y0W433e000k

It's creating TODOs and not the itens inside the "#1 - Candidatos novos" TODO list...  Look: https://basecamp.com/1867355/projects/2750547

Have you really tested it before send to me?

**Comment by obetomuniz** [comment]
@mergulhao I applied changes in Zapier to add items to an existing TO-DO list (#1 - Candidatos novos). But in task list, you said, "..post on candidates Basecamp ...", that is, did not specify where.

Regarding the redirection after posting, I thought it was due to the new implementation, since it was not specified the behavior.

I ask you more details in next tasks about everything must be done to avoid confusion in tests or unexpected behavior.

Now, this works! Can you check?

#thx

**Comment by mergulhao** [comment]
@obetomuniz Cool! Is it possible to delivery the Basecamp e-mail? Like this one: http://cl.ly/image/3W1v1T1y0S31

**Comment by obetomuniz** [comment]
@mergulhao Yes, Is it possible, but I need get an unique mail to receive and share with the team. Also too I can list all email address, I just need of an list emails for this. We have a default mail for share? It is tech@helabs.com.br?

**Comment by mergulhao** [comment]
@obetomuniz With our current Webhooks project (see https://github.com/Helabs/webhooks) we get all e-mails from Basecamp api. Maybe you can do the same... As I know it looks for all participants on the "Candidatos" project and check everyone.

Refs:
https://github.com/Helabs/webhooks/blob/master/app/services/basecamp_wuffo_candidate.rb#L38
https://github.com/Helabs/webhooks/blob/master/app/services/basecamp.rb#L69

**Comment by obetomuniz** [comment]
@mergulhao We have a problem! I send an email after creating an item in the TO-DO List, but I can't put in the email body the contents of the first comment. The Zapier only able to apply the item name.

I tried some alternatives, but unfortunately it did not work.

Another proposal would be to send an email directly from Wufoo, but in this case, all the integration happens when sending emails using Basecamp Notifications is lost.

In this case, the webhooks is more customizable, because we do have control of it.

NOTE: You would know if in the Basecamp there some setting to send notifications when it was created an item in a TO-DO list?

**Comment by mergulhao** [comment]
Ok. I update zapier to assign the todo to @eduardofiorezi. This way he is notified.
