### ISSUE TITLE
Improve redirect signal

### ISSUE THREAD

**Issue by tomasmuller** [Helabs/helabs.github.com#550]
Can we improve this redirect signal?

![](https://s3-sa-east-1.amazonaws.com/uploads-br.hipchat.com/17122/593622/pfapdlsPnSqP5DW/Screen_Shot_2015-01-23_at_10_23_47_AM_png.png)

Happens every time accessing helabs.com.br. 
Accessing "helabs.com" also, but it just blink on screen and the site appears.

**Comment by marcioc0sta** [comment]
@tomasmuller i'll check it as soon as i can ;)

**Comment by obetomuniz** [comment]
@tomasmuller and @marcioc0sta ... Check this issue: https://github.com/jekyll/jekyll-redirect-from/issues/55 

...We use this gem to do the redirect, I think that can't customize the page.

**Comment by marcioj** [comment]
Maybe we could reopen [this method](https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect_page.rb#L19), and use our desired html :hammer:

**Comment by rafaelp** [comment]
Gente, pelo amor de Deus, é só criar um index.html

**Comment by maurogeorge** [comment]
Guys,

I fixed this on https://github.com/Helabs/helabs.github.com/commit/7cefe5bb19079971e07fd93c16e79ca956bcc8ef. I keep the `jekyll-redirect-from` I think this is used in other places because we have a lot of `redirect_from`.

This fixes only the home page, if you access a old link like the http://helabs.com.br/nosso-time/ you still see the redirect message, I think this is a common behavior as you can see on the https://help.github.com/enterprise for example.

I will keep this issue open to someone review and close this issue.
